/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empat.kelasku.ui.view.components;

import com.empat.kelasku.util.ImageResizer;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.border.MatteBorder;
import java.awt.Color;
import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Font;
/**
 *
 * @author ihsan
 */
public class CustomCardComponent extends javax.swing.JPanel {

    /**
     * Creates new form NewJFrame
     */
    public CustomCardComponent(String namaKelas) {
    	this.namaKelas = namaKelas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon moreIcon = ImageResizer.resizeIcon(CustomCardComponent.class.getResource("/images/education.png"), 25, 25);
        setLayout(new BorderLayout(0, 0));
        
        JLabel lblNamaKelas = new JLabel(namaKelas);
        lblNamaKelas.setFont(new Font("Dialog", Font.BOLD, 17));
        lblNamaKelas.setHorizontalAlignment(SwingConstants.CENTER);
        add(lblNamaKelas, BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    public String namaKelas;
}
